# Generated by Django 3.0.8 on 2020-07-28 16:01

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(807), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn1_ability',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn1_held_item',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn1_move1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn1_move2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn1_move3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn1_move4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn1_nature',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn1_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn2_ability',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn2_held_item',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn2_move1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn2_move2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn2_move3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn2_move4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn2_nature',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn2_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn3_ability',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn3_held_item',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn3_move1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn3_move2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn3_move3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn3_move4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn3_nature',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn3_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn4_ability',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn4_held_item',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn4_move1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn4_move2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn4_move3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn4_move4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn4_nature',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn4_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn5_ability',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn5_held_item',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn5_move1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn5_move2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn5_move3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn5_move4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn5_nature',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn5_number',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn6_ability',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn6_held_item',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn6_move1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn6_move2',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn6_move3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn6_move4',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn6_nature',
        ),
        migrations.RemoveField(
            model_name='team',
            name='pkmn6_number',
        ),
        migrations.AddField(
            model_name='team',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='Team_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.IntegerField(validators=[django.core.validators.MaxValueValidator(293), django.core.validators.MinValueValidator(1)])),
                ('held_item', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1018), django.core.validators.MinValueValidator(1)])),
                ('nature', models.IntegerField(validators=[django.core.validators.MaxValueValidator(25), django.core.validators.MinValueValidator(1)])),
                ('move1', models.IntegerField(validators=[django.core.validators.MaxValueValidator(746), django.core.validators.MinValueValidator(1)])),
                ('move2', models.IntegerField(validators=[django.core.validators.MaxValueValidator(746), django.core.validators.MinValueValidator(1)])),
                ('move3', models.IntegerField(validators=[django.core.validators.MaxValueValidator(746), django.core.validators.MinValueValidator(1)])),
                ('move4', models.IntegerField(validators=[django.core.validators.MaxValueValidator(746), django.core.validators.MinValueValidator(1)])),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambuilder.Pokemon')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teambuilder.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='teambuilder.Team_member', to='teambuilder.Pokemon'),
        ),
    ]
