# Generated by Django 3.0.8 on 2020-07-30 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0003_auto_20200728_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='held_item',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(954), django.core.validators.MinValueValidator(1)]),
        ),
    ]
