# Generated by Django 3.0.8 on 2020-07-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0004_auto_20200730_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team_member',
            name='ability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='held_item',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='move1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='move2',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='move3',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='move4',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team_member',
            name='nature',
            field=models.CharField(max_length=50),
        ),
    ]
