# Generated by Django 3.0.8 on 2020-08-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teambuilder', '0005_auto_20200730_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
